status = WARN
name = HmsProxyLog4j2

appenders = console

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{ISO8601} %5p [%t] %c{2}: %m%n

rootLogger.level = info
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = console

logger.hmsproxy.name = io.github.mmalykhin.hmsproxy
logger.hmsproxy.level = debug
logger.hmsproxy.additivity = false
logger.hmsproxy.appenderRefs = console
logger.hmsproxy.appenderRef.console.ref = console
